const frasesAleatorias = [
  "A vida é uma jornada, não um destino.",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  "Acredite em você mesmo e tudo é possível.",
  "A única maneira de fazer um ótimo trabalho é amar o que você faz.",
  "A persistência é o caminho do êxito.",
  "A cada novo dia, um novo começo.",
  "O segredo para progredir é começar.",
  "O que não te desafia, não te transforma.",
  "O futuro pertence àqueles que acreditam na beleza de seus sonhos.",
  "Nunca é tarde demais para ser o que você poderia ter sido.",
  "O verdadeiro poder é a capacidade de dizer não.",
  "Você é mais forte do que pensa.",
  "A vida é curta, aproveite cada momento.",
  "A gratidão é a chave para a felicidade.",
  "Tudo é possível para aquele que acredita.",
  "A melhor maneira de prever o futuro é criá-lo.",
  "O otimismo é a fé que leva à realização.",
  "O sucesso não é a chave para a felicidade. A felicidade é a chave para o sucesso.",
  "A coragem não é a ausência do medo, mas o triunfo sobre ele.",
  "A única coisa necessária para o triunfo do mal é que os homens de bem não façam nada.",
  "A criatividade é a inteligência se divertindo.",
  "A imaginação é mais importante do que o conhecimento.",
  "A simplicidade é a sofisticação máxima.",
  "Tudo o que você pode imaginar é real.",
  "A beleza está nos olhos de quem vê.",
  "Você é a média das cinco pessoas com quem mais convive.",
  "O conhecimento é poder.",
  "Seja a mudança que você quer ver no mundo.",
  "A vida começa no fim da sua zona de conforto.",
  "O segredo do negócio é saber alguma coisa que mais ninguém sabe.",
  "Nunca desista, pois é isso que os vencedores fazem.",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  "O que você coloca em sua mente todos os dias é o que se torna realidade.",
  "O talento vence jogos, mas o trabalho em equipe e a inteligência vencem campeonatos.",
  "A vida é feita de escolhas.",
  "Acredite em si mesmo e tudo será possível.",
  "Você não pode atravessar o oceano apenas olhando para a água.",
  "A sorte favorece os preparados.",
  "A melhor vingança é o sucesso.",
  "O tempo é uma criação da mente.",
  "A criatividade é a inteligência se divertindo.",
  "Nada é impossível, a palavra em si diz 'eu sou possível'.",
  "A sorte favorece a mente preparada.",
  "O que não te desafia, não te faz mudar.",
  "A paixão é a energia que nos mantém vivos.",
  "A melhor vingança é um sucesso estrondoso.",
  "A confiança em si mesmo é o primeiro segredo do sucesso.",
  "Seja a mudança que você deseja ver no mundo.",
  "Sua única limitação é você mesmo.",
  "Nunca é tarde demais para ser o que você poderia ter sido.",
  "Sonhe grande e ouse falhar.",
  "Não importa quantas vezes você falhe, você só precisa acertar uma vez.",
  "Acredite que você pode e você está no meio do caminho.",
  "O que você pensa, você se torna.",
  "Seja você mesmo; todos os outros já estão ocupados.",
  "Nada é permanente, exceto a mudança.",
  "A vida é curta, sorria enquanto você ainda tem dentes.",
  "O impossível é apenas uma palavra usada por pessoas preguiçosas que têm medo de tentar.",
  "O sucesso é uma caminhada, não uma corrida.",
  "Grandes coisas nunca vêm de zonas de conforto.",
  "A sorte é o que acontece quando a preparação encontra a oportunidade.",
  "O fracasso é o caminho para o sucesso.",
  "A ação é a chave para todo o sucesso.",
  "A vida é uma aventura ousada ou nada.",
  "A melhor maneira de prever o futuro é criá-lo.",
  "Você é a média das cinco pessoas com as quais mais convive.",
  "A disciplina é a ponte entre metas e realizações.",
  "A gentileza é uma linguagem que os surdos podem ouvir e os cegos podem ver.",
  "Não importa quem você é, você pode fazer a diferença.",
  "Não existe caminho para a felicidade. A felicidade é o caminho.",
  "A mente é tudo. Você se torna aquilo que você pensa.",
  "A coragem é a resistência ao medo, domínio do medo - não a ausência do medo.",
];

function fraseAleatoria() {
  const indice = Math.floor(Math.random() * frasesAleatorias.length);
  return frasesAleatorias[indice];
}
module.exports = fraseAleatoria;
